site_name: AI Courses
repo_url: https://github.com/FAIRmat-NFDI/ai-courses
repo_name: FAIRmat-NFDI/ai-courses

theme:
  name: material
  logo: assets/nomad-infrastructure.svg
  favicon: images/favicon.png
  palette:
    primary: custom
  icon:
    repo: fontawesome/brands/github-alt
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Gyzx3ukUw8

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg